from typing import Annotated
from uuid import UUID
from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import AuthenticatedUser, get_current_user
from app.db.session import get_db
from app.schemas.category import CategoryCreate, CategoryUpdate, UserCategoryResponse
from app.schemas.envelope import ResponseEnvelope
from app.services.category_service import create_category, delete_category, get_user_categories, update_category

router = APIRouter()


@router.post("/", response_model=ResponseEnvelope[UserCategoryResponse], status_code=201)
async def post_category(
    payload: CategoryCreate,
    current_user: Annotated[AuthenticatedUser, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
) -> ResponseEnvelope[UserCategoryResponse]:
    """Create an owned custom category. Slug/color are generated by the server."""
    category = await create_category(db, current_user.id, payload)
    return ResponseEnvelope(data=UserCategoryResponse.model_validate(category))


@router.patch("/{category_id}", response_model=ResponseEnvelope[UserCategoryResponse])
async def patch_category(
    category_id: UUID,
    payload: CategoryUpdate,
    current_user: Annotated[AuthenticatedUser, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
) -> ResponseEnvelope[UserCategoryResponse]:
    """Rename/recolor own category by ID; preserve its slug and expense references."""
    category = await update_category(db, current_user.id, category_id, payload)
    return ResponseEnvelope(data=UserCategoryResponse.model_validate(category))


@router.delete("/{category_id}", response_model=ResponseEnvelope[None])
async def remove_category(
    category_id: UUID,
    current_user: Annotated[AuthenticatedUser, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
) -> ResponseEnvelope[None]:
    """Hard-delete own category after checking usage; retain existing expense slugs.

    Preserves the original frontend's deletion/fallback behavior. Reference count
    is returned in meta; referenced expenses are neither deleted nor recategorized.
    """
    references = await delete_category(db, current_user.id, category_id)
    return ResponseEnvelope(meta={"referencing_expenses": references, "expense_categories_preserved": True})


@router.get("/", response_model=ResponseEnvelope[list[UserCategoryResponse]])
async def list_user_categories(
    current_user: Annotated[AuthenticatedUser, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
) -> ResponseEnvelope[list[UserCategoryResponse]]:
    """
    Authenticated endpoint returning categories belonging strictly to the current user.
    Authorization rule: user_id == current_user.id.
    """
    categories = await get_user_categories(db, current_user.id)
    return ResponseEnvelope(
        data=[UserCategoryResponse.model_validate(c) for c in categories],
        error=None,
        meta={"count": len(categories)},
    )
